//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "logins")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub email: String,
    pub login: String,
    pub pass: String,
    pub phone_number: i64,
    pub create_date: DateTime,
    pub modifate_date: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::personalaccount::Entity")]
    Personalaccount,
}

impl Related<super::personalaccount::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Personalaccount.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
